# Generated by Django 4.1.5 on 2023-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('team', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('average', models.IntegerField()),
                ('batting_order', models.CharField(max_length=30)),
            ],
        ),
    ]
